run:
  tests: false
  timeout: 10m
issues:
  exclude: 
    - ST1000
  fix: true 
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    # Default: 30
    max-func-lines: 10
  revive:
    enable-all-rules: true
    # Disabled rules
    rules:
      - name: blank-imports
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: add-constant
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: bare-return
        disabled: true
      - name: redundant-import-alias
        disabled: true
      - name: comment-spacings
        disabled: true
  gocritic:
    disabled-checks:
      - commentedOutCode
      - docStub
      - hugeParam
      - whyNoLint
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  sloglint:
    no-mixed-args: true
    attr-only: true
    context: all
    static-msg: false 
    key-naming-case: snake
linters:
  enable:
    - wrapcheck
    - gosimple
    - whitespace
    - gofumpt
    - revive
    - godot
    - errcheck
    - gosec
    - gochecknoglobals
    - staticcheck
    - govet
    - unused
    - ineffassign
    - typecheck
    - revive
    - bodyclose
    - durationcheck
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - goconst
    - gocritic
    - makezero
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - makezero
    - musttag
    - gocheckcompilerdirectives
    - importas
    - reassign
    - rowserrcheck
    - usestdlibvars
    - nakedret
    - sloglint
