FROM golang:1.25.1-alpine

RUN apk update && \
    apk add --no-cache \
    git \
    bash \
    curl \
    alpine-sdk \
    ca-certificates

RUN go install github.com/bokwoon95/wgo@latest
RUN curl -sSf https://atlasgo.sh | sh
WORKDIR /app
COPY . .
RUN go mod download 

COPY . .

EXPOSE 8181
