// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=mock/publisher_mocks.go -package mock_pubsub
//

// Package mock_pubsub is a generated GoMock package.
package mock_pubsub

import (
	context "context"
	reflect "reflect"

	pubsub "github.com/buni/tx-parser/internal/pkg/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, msg *pubsub.Message, opts ...pubsub.PublishOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), varargs...)
}

// MockPublisherWithEvent is a mock of PublisherWithEvent interface.
type MockPublisherWithEvent struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherWithEventMockRecorder
	isgomock struct{}
}

// MockPublisherWithEventMockRecorder is the mock recorder for MockPublisherWithEvent.
type MockPublisherWithEventMockRecorder struct {
	mock *MockPublisherWithEvent
}

// NewMockPublisherWithEvent creates a new mock instance.
func NewMockPublisherWithEvent(ctrl *gomock.Controller) *MockPublisherWithEvent {
	mock := &MockPublisherWithEvent{ctrl: ctrl}
	mock.recorder = &MockPublisherWithEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherWithEvent) EXPECT() *MockPublisherWithEventMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisherWithEvent) Publish(ctx context.Context, msg *pubsub.Message, opts ...pubsub.PublishOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherWithEventMockRecorder) Publish(ctx, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisherWithEvent)(nil).Publish), varargs...)
}
